"""Curated task -> HF dataset mappings. Demo safety net for the research agent."""

CATALOG: list[dict] = [
    {
        "task_tags": ["summarization", "legal", "contracts", "documents"],
        "hf_dataset": "FiscalNote/billsum",
        "dataset_config": None,
        "dataset_split": "train[:2000]",
        "input_field": "text",
        "output_field": "summary",
        "description": "US Congressional bills with human-written summaries. Strong style signal.",
    },
    {
        "task_tags": ["summarization", "news", "articles"],
        "hf_dataset": "abisee/cnn_dailymail",
        "dataset_config": "3.0.0",
        "dataset_split": "train[:2000]",
        "input_field": "article",
        "output_field": "highlights",
        "description": "CNN/DailyMail news article summarization.",
    },
    {
        "task_tags": ["summarization", "dialogue", "chat", "conversation"],
        "hf_dataset": "knkarthick/samsum",
        "dataset_config": None,
        "dataset_split": "train[:2000]",
        "input_field": "dialogue",
        "output_field": "summary",
        "description": "Messenger-like conversation summarization.",
    },
    {
        "task_tags": ["instruction-following", "general", "assistant"],
        "hf_dataset": "yahma/alpaca-cleaned",
        "dataset_config": None,
        "dataset_split": "train[:3000]",
        "input_field": "instruction",
        "output_field": "output",
        "description": "Cleaned Alpaca instruction-following dataset.",
    },
    {
        "task_tags": ["code", "python", "programming", "coding"],
        "hf_dataset": "sahil2801/CodeAlpaca-20k",
        "dataset_config": None,
        "dataset_split": "train[:3000]",
        "input_field": "instruction",
        "output_field": "output",
        "description": "Code generation instruction dataset.",
    },
    {
        "task_tags": ["math", "reasoning", "arithmetic", "word-problems"],
        "hf_dataset": "openai/gsm8k",
        "dataset_config": "main",
        "dataset_split": "train[:2000]",
        "input_field": "question",
        "output_field": "answer",
        "description": "Grade-school math word problems with chain-of-thought.",
    },
    {
        "task_tags": ["sql", "text-to-sql", "database"],
        "hf_dataset": "b-mc2/sql-create-context",
        "dataset_config": None,
        "dataset_split": "train[:3000]",
        "input_field": "question",
        "output_field": "answer",
        "description": "Natural language questions to SQL queries with table context.",
    },
    {
        "task_tags": ["question-answering", "qa", "reading-comprehension"],
        "hf_dataset": "rajpurkar/squad",
        "dataset_config": None,
        "dataset_split": "train[:2000]",
        "input_field": "question",
        "output_field": "answers",
        "description": "SQuAD reading-comprehension QA.",
    },
    {
        "task_tags": ["function-calling", "tools", "agents"],
        "hf_dataset": "Salesforce/xlam-function-calling-60k",
        "dataset_config": None,
        "dataset_split": "train[:2000]",
        "input_field": "query",
        "output_field": "answers",
        "description": "Function-calling / tool-use dataset.",
    },
    {
        "task_tags": ["medical", "clinical", "healthcare"],
        "hf_dataset": "medalpaca/medical_meadow_medqa",
        "dataset_config": None,
        "dataset_split": "train[:2000]",
        "input_field": "instruction",
        "output_field": "output",
        "description": "Medical QA from USMLE-style questions.",
    },
    {
        "task_tags": ["persona", "character", "roleplay", "style"],
        "hf_dataset": "PygmalionAI/PIPPA",
        "dataset_config": None,
        "dataset_split": "train[:2000]",
        "input_field": "conversation",
        "output_field": "response",
        "description": "Persona-driven roleplay conversations. Strong style signal.",
    },
    {
        "task_tags": ["json", "structured-output", "extraction"],
        "hf_dataset": "NousResearch/json-mode-eval",
        "dataset_config": None,
        "dataset_split": "train[:1000]",
        "input_field": "prompt",
        "output_field": "completion",
        "description": "JSON-mode structured output training data.",
    },
]
